name: flutter_auth_app
description: A simple Flutter app for login.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  provider: ^6.0.5
  flutter:
    sdk: flutter
  http: ^1.1.0 # Para hacer solicitudes HTTP
  jwt_decoder: ^2.0.1
  go_router: ^15.1.1
  shared_preferences: ^2.0.15
  crypto: ^3.0.0
  flutter_localizations: # Agregar soporte para localización
    sdk: flutter
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

